#!/usr/bin/env bash

JSON_QUERY=$(cat <<JQ
.data.page | {
  groups: .groups | map({
    name: .name,
    meals: .meals | map({
      name: .name,
      price: .price | ltrimstr("€ ") | gsub(","; ".") | split("/") | map(tonumber) | {
        student: .[0],
        employee: .[1],
        guest: .[2]
      },
      tags: .icons | map(
        if .src == "/vendor/infomax/mensen/icons/1.png" then "vegetarian"
        elif .src == "/vendor/infomax/mensen/icons/15.png" then "vegan"
        elif .src == "/vendor/infomax/mensen/icons/18.png" then "organic"
        elif .src == "/vendor/infomax/mensen/icons/38.png" then "sustainable fishing"
        elif .src == "/vendor/infomax/mensen/icons/43.png" then "climate"
        elif .src == "/vendor/infomax/mensen/icons/ampel_gelb_70x65.png" then "yellow"
        elif .src == "/vendor/infomax/mensen/icons/ampel_gruen_70x65.png" then "green"
        elif .src == "/vendor/infomax/mensen/icons/ampel_rot_70x65.png" then "red"
        else .src
        end),
      allergens: .allergens | map({
        allergen: {
          code: .allergen | .[0].value,
          name: .allergen | .[1].value
        }
      })
    })
  })
}
JQ
)

cat example.json | jq "$JSON_QUERY" | python3 frontend.py $*
